baseURL = "https://rafasacaan.com/"
languageCode = "en-us"
title = "rafasacaan"
theme = "dario"

[params]
  author = "rafa sacaan"
  description = "Mi blog"
  
  [author]
    email = "rafasacaan@gmail.com"
  
  [params.homeInfoParams]
    #Title = "rafa sacaan"
    Content = """Hola, soy Rafa. 
    \nTrabajo como consultor
    usando herramientas de ML y AI para ayudar a personas y empresas a tomar mejores decisiones 
    mediante datos y tecnología.
    \nMe gusta combinar metodología, intuición y creatividad para encontrar soluciones que traigan algún impacto. 
    \nPara mí, lo más importante es encontrarnos en un sentido de porqué hacemos algo. Más aun, es encontrarnos en la dimensión humana, que es donde se cocinan las cosas.
    \nTambién me gusta perderme grabando música de las formas más raras posibles. Puedes ver mi micro estudio musical llamado MUNRA.
    \nContáctame si quieres en [rafasacaan@gmail.com](mailto:rafasacaan@gmail.com)
    \nEncuentra mi micro estudio en [munra.cl](https://www.munra.cl)
    """
    
    Description = "Mi blog."
